import { PrismaPg } from "@prisma/adapter-pg";
import { PrismaClient } from "../src/generated/prisma/client";

const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL! });
const prisma = new PrismaClient({ adapter });

const tickets = [
  // Refund requests
  { subject: "Refund for cancelled order #8821", body: "Hi, I cancelled my order 3 days ago but still haven't received my refund. Order total was $149.99. Please advise.", fromName: "Sarah Mitchell", fromEmail: "sarah.mitchell@gmail.com", status: "open", category: "refund_request", daysAgo: 1 },
  { subject: "Double charged for subscription renewal", body: "I was charged twice this month for my Pro subscription. Both charges appeared on my credit card on the 3rd. Please refund the duplicate.", fromName: "James Kowalski", fromEmail: "jkowalski@hotmail.com", status: "resolved", category: "refund_request", daysAgo: 5 },
  { subject: "Wrong item received – want a refund", body: "I ordered a blue Large hoodie but received a red Medium. I'd prefer a full refund rather than an exchange as I needed it for an event this weekend.", fromName: "Priya Nair", fromEmail: "priya.nair@outlook.com", status: "open", category: "refund_request", daysAgo: 2 },
  { subject: "Refund request – product damaged on arrival", body: "The ceramic vase I ordered arrived shattered. Photos attached. Please process a full refund to my original payment method.", fromName: "Tom Hargreaves", fromEmail: "tomharg@yahoo.com", status: "closed", category: "refund_request", daysAgo: 14 },
  { subject: "Accidental purchase – please refund", body: "My 8-year-old accidentally purchased an annual plan using my saved card. I noticed this morning. Could you please cancel and refund?", fromName: "Lisa Fernandez", fromEmail: "lisaf@icloud.com", status: "open", category: "refund_request", daysAgo: 0 },
  { subject: "Still waiting on refund from 2 weeks ago", body: "I submitted a refund request on the 5th (ticket #4421) and was told 5-7 business days. It has now been 14 days with no refund.", fromName: "Marcus Webb", fromEmail: "marcus.webb@gmail.com", status: "open", category: "refund_request", daysAgo: 1 },
  { subject: "Subscription cancellation + refund", body: "I cancelled my subscription immediately after renewing by mistake. The cancellation went through but I have not received a pro-rated refund for the unused period.", fromName: "Yuki Tanaka", fromEmail: "yuki.tanaka@me.com", status: "resolved", category: "refund_request", daysAgo: 8 },
  { subject: "Refund for duplicate orders", body: "I placed the same order twice due to a website error showing a failed payment. Both orders shipped. I'm happy to return one, please advise on the return label and refund.", fromName: "Carlos Mendez", fromEmail: "cmendez82@gmail.com", status: "open", category: "refund_request", daysAgo: 3 },

  // Technical questions
  { subject: "App crashes on launch after latest update", body: "Since updating to version 4.2.1 this morning, the app crashes immediately on launch on my iPhone 14. I've tried reinstalling but the issue persists.", fromName: "Hannah Osei", fromEmail: "hannah.osei@gmail.com", status: "open", category: "technical_question", daysAgo: 0 },
  { subject: "Two-factor authentication not sending SMS", body: "I enabled 2FA last week and it was working fine. Since yesterday, I'm no longer receiving the SMS code. I've verified my phone number is correct.", fromName: "Daniel Park", fromEmail: "dpark.dev@gmail.com", status: "open", category: "technical_question", daysAgo: 1 },
  { subject: "CSV export contains incorrect data", body: "When I export my transaction history to CSV, some entries appear duplicated and a few amounts are wrong. The in-app view looks correct. This is affecting our accounting.", fromName: "Rachel Okonkwo", fromEmail: "r.okonkwo@financegroup.co", status: "open", category: "technical_question", daysAgo: 2 },
  { subject: "Cannot connect to API – 403 errors", body: "We integrated your API last month with no issues. Starting today we're getting 403 Forbidden on all endpoints. Our API key hasn't changed. Is there an issue on your end?", fromName: "Ethan Clarke", fromEmail: "ethan@devhive.io", status: "resolved", category: "technical_question", daysAgo: 6 },
  { subject: "Dashboard not loading on Firefox", body: "The dashboard loads fine in Chrome and Safari, but in Firefox it shows a blank white screen with a console error: 'Cannot read properties of undefined'. Firefox version 121.0.", fromName: "Sofia Larsson", fromEmail: "sofia.larsson@nordic.se", status: "open", category: "technical_question", daysAgo: 3 },
  { subject: "Email notifications stopped working", body: "I used to receive email notifications for new comments on my posts. This stopped about a week ago. I've checked my notification settings and everything appears enabled.", fromName: "Ahmed Hassan", fromEmail: "a.hassan@protonmail.com", status: "open", category: "technical_question", daysAgo: 4 },
  { subject: "Search returning no results for existing items", body: "The search function is broken. Searching for items I can clearly see in the list returns 'No results found'. This started after the maintenance window on Tuesday.", fromName: "Nina Becker", fromEmail: "nina.becker@berlin.de", status: "resolved", category: "technical_question", daysAgo: 10 },
  { subject: "Webhook events not being delivered", body: "Our webhook endpoint is correctly configured and responding with 200 status, but we're not receiving any events since 2pm yesterday. We need this for our real-time processing pipeline.", fromName: "Raj Patel", fromEmail: "raj@techstack.in", status: "open", category: "technical_question", daysAgo: 1 },
  { subject: "Unable to upload files larger than 5MB", body: "The file upload feature fails silently for files above approximately 5MB. The progress bar completes but the file never appears in storage. I've tested with multiple browsers.", fromName: "Claire Dubois", fromEmail: "cdubois@creativestudio.fr", status: "open", category: "technical_question", daysAgo: 2 },
  { subject: "SSO integration failing with Okta", body: "We're trying to configure SSO with Okta as the identity provider. Authentication succeeds on the Okta side but we receive a 'Invalid SAML response' error when redirected back.", fromName: "Kevin O'Brien", fromEmail: "kobrien@enterprise-inc.com", status: "open", category: "technical_question", daysAgo: 0 },
  { subject: "Dark mode not persisting between sessions", body: "I set the app to dark mode and it works fine within the session. However, every time I close and reopen the app it reverts back to light mode despite the setting being saved.", fromName: "Amara Diallo", fromEmail: "amara.diallo@outlook.com", status: "resolved", category: "technical_question", daysAgo: 12 },
  { subject: "Bulk import CSV failing at row 847", body: "I'm trying to import a 2000 row CSV. It processes up to row 847 then fails with 'Unexpected error'. Rows 1–846 are imported successfully. The row 847 data looks normal to me.", fromName: "Steve Nakamura", fromEmail: "steve.n@logistics-co.jp", status: "open", category: "technical_question", daysAgo: 1 },
  { subject: "Mobile app login loop on Android 14", body: "After updating to Android 14, the app enters an infinite login loop. Entering credentials successfully redirects to the login screen again. Other users in our team have the same issue.", fromName: "Fatima Al-Rashidi", fromEmail: "fatima.alrashidi@gmail.com", status: "open", category: "technical_question", daysAgo: 3 },
  { subject: "Calendar sync not working with Google Calendar", body: "I connected my Google Calendar 3 days ago. Events created in your app are not appearing in Google Calendar. The sync status shows 'Connected' but nothing is syncing.", fromName: "Hugo Silva", fromEmail: "h.silva@porto.pt", status: "open", category: "technical_question", daysAgo: 3 },
  { subject: "Rate limit errors on legitimate traffic", body: "We're hitting rate limit errors (429) during normal business hours with traffic levels well within our plan limits. We're on the Business tier allowing 1000 req/min. Our peak is ~200.", fromName: "Mei Lin", fromEmail: "mei.lin@databridge.com.cn", status: "open", category: "technical_question", daysAgo: 0 },
  { subject: "Payment widget not rendering on mobile", body: "The embedded payment widget renders correctly on desktop but on mobile devices it appears as a small collapsed box that users cannot interact with. Affects iOS and Android browsers.", fromName: "Omar Farooq", fromEmail: "omar.farooq@ecommerce-bd.com", status: "resolved", category: "technical_question", daysAgo: 9 },
  { subject: "Reports showing data from wrong date range", body: "The monthly report for March is showing data that appears to include entries from February. Totals don't match what I can see when filtering manually. Could be a timezone issue.", fromName: "Ingrid Hoffmann", fromEmail: "ingrid.h@analytics-eu.de", status: "open", category: "technical_question", daysAgo: 5 },

  // General questions
  { subject: "What payment methods do you accept?", body: "I'm looking to upgrade my plan but I can only pay with PayPal or bank transfer. Your checkout only shows card options. Do you support alternative payment methods?", fromName: "Patrick Nguyen", fromEmail: "patng@gmail.com", status: "resolved", category: "general_question", daysAgo: 7 },
  { subject: "How do I add team members to my account?", body: "I have a Team plan but I can't find where to invite colleagues. I've looked through Settings but there's no 'Team' or 'Members' section visible to me.", fromName: "Zara Ahmed", fromEmail: "z.ahmed@designco.ae", status: "resolved", category: "general_question", daysAgo: 4 },
  { subject: "Can I export my data before cancelling?", body: "I'm considering cancelling my subscription and want to make sure I can export all my data first. What formats are available and is there any limitation on the amount I can export?", fromName: "Bruno Rossi", fromEmail: "b.rossi@milan.it", status: "resolved", category: "general_question", daysAgo: 11 },
  { subject: "Is there a free trial for the Enterprise plan?", body: "We're evaluating your Enterprise plan for a team of 200. Is it possible to get a 30-day trial before committing? We'd need SSO, audit logs, and dedicated support.", fromName: "Jennifer Walsh", fromEmail: "jwalsh@bigcorp.com", status: "open", category: "general_question", daysAgo: 1 },
  { subject: "Do you have a mobile app?", body: "I can see the web app works on mobile browser but is there a dedicated iOS/Android app? I couldn't find it in the App Store.", fromName: "Liam O'Connor", fromEmail: "liam.oc@personal.ie", status: "resolved", category: "general_question", daysAgo: 6 },
  { subject: "How long is data retained after cancellation?", body: "According to your privacy policy data is retained for 90 days. Does this apply to all data including attachments and audit logs? We need to understand this for compliance purposes.", fromName: "Valentina Cruz", fromEmail: "vcruz@legal-firm.mx", status: "open", category: "general_question", daysAgo: 2 },
  { subject: "Can I change my billing cycle from monthly to annual?", body: "I'm currently on a monthly Pro plan. I'd like to switch to annual billing to get the discount. How do I do this and will I be charged the difference immediately?", fromName: "Dylan Roberts", fromEmail: "dylan.r@freelance.co.uk", status: "resolved", category: "general_question", daysAgo: 8 },
  { subject: "Is there an API rate limit for the free tier?", body: "I'm building a small side project using the free tier. What are the API rate limits? I need to understand if the free tier will be sufficient before deciding to upgrade.", fromName: "Aisha Kamara", fromEmail: "aisha.kamara@techlearn.org", status: "resolved", category: "general_question", daysAgo: 15 },
  { subject: "Do you offer discounts for non-profits?", body: "I run a non-profit organisation and am interested in your Team plan. Do you offer a discount for registered non-profits? We're a small team of 8.", fromName: "Gregory Thompson", fromEmail: "greg@communityhelp.org", status: "open", category: "general_question", daysAgo: 3 },
  { subject: "What's the difference between the Pro and Business plans?", body: "I've read the pricing page but I'm not sure which plan is right for us. We're a team of 15, need audit logs, and require SSO. Could someone help clarify?", fromName: "Nadia Volkov", fromEmail: "nadia.v@startup-ru.com", status: "resolved", category: "general_question", daysAgo: 9 },
  { subject: "How do I transfer ownership of my account?", body: "I'm leaving my company and the account is registered under my email. How do I transfer ownership to my colleague without losing any data or settings?", fromName: "Joshua Kim", fromEmail: "j.kim@agency.kr", status: "open", category: "general_question", daysAgo: 0 },
  { subject: "Do you support GDPR data deletion requests?", body: "One of our EU customers has submitted a right-to-erasure request. How do we delete their data from your platform? Is there a self-service option or do we need to contact support?", fromName: "Annika Berg", fromEmail: "annika.berg@gdpr-consulting.se", status: "open", category: "general_question", daysAgo: 1 },
  { subject: "Can I use the same account on multiple devices?", body: "I work between my laptop and desktop. Can I be logged into the same account on both at the same time without issues?", fromName: "Mohamed Saleh", fromEmail: "m.saleh@cairo.eg", status: "resolved", category: "general_question", daysAgo: 13 },
  { subject: "Is there an offline mode?", body: "I frequently work on trains with no internet. Is there any offline functionality or a way to cache data for offline use?", fromName: "Chloe Petit", fromEmail: "chloe.petit@remote-worker.fr", status: "open", category: "general_question", daysAgo: 4 },
  { subject: "How do I set up automatic backups?", body: "I want to ensure my data is automatically backed up. Is there a built-in backup feature or do I need to set up scheduled exports manually?", fromName: "Ivan Petrov", fromEmail: "i.petrov@datacare.bg", status: "resolved", category: "general_question", daysAgo: 20 },
  { subject: "What is your uptime SLA?", body: "We're a B2B company considering your Business plan. Before signing we need to know your uptime SLA commitment and what compensation is offered if the SLA is breached.", fromName: "Sandra Okafor", fromEmail: "s.okafor@enterprise-ng.com", status: "open", category: "general_question", daysAgo: 2 },
  { subject: "Are there any training resources available?", body: "We've just onboarded 20 new users. Is there documentation, video tutorials, or a knowledge base we can direct them to? Ideally something they can self-serve.", fromName: "Felix Braun", fromEmail: "fbraun@company.at", status: "resolved", category: "general_question", daysAgo: 5 },
  { subject: "Can we get a dedicated account manager?", body: "We're on the Enterprise plan and our team has grown to 500 users. We'd like a dedicated point of contact for support and account management. Is this available?", fromName: "Lucia Moreno", fromEmail: "lucia.moreno@latam-corp.co", status: "open", category: "general_question", daysAgo: 1 },

  // More technical
  { subject: "OAuth2 redirect URI mismatch error", body: "I'm getting 'redirect_uri_mismatch' when attempting OAuth2 authorisation. I've checked the configured redirect URIs in the dashboard and they match exactly what I'm sending.", fromName: "Alex Turner", fromEmail: "alex.turner@devtools.co", status: "open", category: "technical_question", daysAgo: 0 },
  { subject: "Pagination not working correctly – skipping records", body: "When paginating through results using offset/limit, some records are being skipped between pages. For example page 1 shows rows 1-10, but page 2 starts at row 12.", fromName: "Yuna Choi", fromEmail: "yuna.choi@software.kr", status: "open", category: "technical_question", daysAgo: 2 },
  { subject: "Emails going to spam after domain change", body: "We recently changed our sending domain. Since then, emails from the platform are landing in customers' spam folders. We've set up SPF and DKIM but the issue persists.", fromName: "Martin Fischer", fromEmail: "m.fischer@mailops.de", status: "open", category: "technical_question", daysAgo: 3 },
  { subject: "Memory leak in embedded JavaScript SDK", body: "We've identified a memory leak when using the JavaScript SDK in a long-running SPA. Memory usage grows continuously over several hours. We can reproduce it consistently.", fromName: "Tara Singh", fromEmail: "t.singh@webtech.in", status: "open", category: "technical_question", daysAgo: 1 },
  { subject: "Timezone issues with scheduled jobs", body: "Scheduled jobs configured for 09:00 are running at the wrong time since daylight saving time changed. It appears the system is using UTC but not accounting for our configured timezone (US/Eastern).", fromName: "Robert Chambers", fromEmail: "rob.chambers@scheduling.us", status: "resolved", category: "technical_question", daysAgo: 18 },
  { subject: "Intermittent 504 timeout on large queries", body: "We're experiencing intermittent 504 Gateway Timeout errors when running complex queries that return more than ~50,000 rows. Smaller queries work fine. Is there a query timeout setting we can adjust?", fromName: "Emile Fontaine", fromEmail: "e.fontaine@datawarehouse.fr", status: "open", category: "technical_question", daysAgo: 4 },
  { subject: "Cannot delete a resource – 422 error", body: "Attempting to delete a specific resource via the API returns a 422 with body: 'Cannot delete resource with active dependencies'. I've checked and there are no active dependencies that I can see.", fromName: "Grace Mensah", fromEmail: "g.mensah@devteam.gh", status: "resolved", category: "technical_question", daysAgo: 7 },
  { subject: "Push notifications not working on iOS 17", body: "Since upgrading to iOS 17, push notifications are no longer received by our users. The app has notification permissions granted. The issue only affects iOS 17, not 16.", fromName: "Chris Matthews", fromEmail: "cmatthews@appdev.au", status: "open", category: "technical_question", daysAgo: 5 },
  { subject: "Table renders incorrectly at 1024px viewport", body: "At exactly 1024px viewport width, the data table loses its horizontal scroll and columns overflow outside the container. Works fine at 1023px and 1025px.", fromName: "Ines Carvalho", fromEmail: "ines.c@frontend.pt", status: "resolved", category: "technical_question", daysAgo: 16 },
  { subject: "Concurrent writes causing data corruption", body: "When two users edit the same record simultaneously, we're seeing data corruption. It appears the last write wins without any conflict detection. We'd expect an optimistic concurrency error.", fromName: "Paul Eriksson", fromEmail: "p.eriksson@saas-nordic.se", status: "open", category: "technical_question", daysAgo: 2 },

  // More refunds
  { subject: "Charged after cancellation", body: "I cancelled my account on the 28th of last month before the billing date. I was still charged on the 1st. Please refund the charge as the cancellation was completed in time.", fromName: "Alice Yamamoto", fromEmail: "alice.y@personal.jp", status: "open", category: "refund_request", daysAgo: 2 },
  { subject: "Promo code was not applied – request refund of difference", body: "I had a 25% discount promo code but the cart didn't accept it at checkout. I completed the purchase at full price. Can you either apply the discount or refund the difference?", fromName: "Ben Foster", fromEmail: "benfoster@gmail.com", status: "resolved", category: "refund_request", daysAgo: 6 },
  { subject: "Subscription not cancelled as requested", body: "I submitted a cancellation request through the in-app form 3 weeks ago but I've now been charged again. I have a screenshot of the confirmation page. Please cancel and refund.", fromName: "Nour Khalil", fromEmail: "n.khalil@beirut.lb", status: "open", category: "refund_request", daysAgo: 1 },
  { subject: "Course content not as advertised – refund requested", body: "The course I purchased was described as 'advanced level' but the content is clearly introductory. I'm requesting a refund under your 30-day guarantee as the product didn't match its description.", fromName: "Gemma Hart", fromEmail: "gemma.hart@learner.co.uk", status: "open", category: "refund_request", daysAgo: 3 },
  { subject: "Refund for unused annual subscription", body: "I purchased an annual plan for a project that got cancelled. I've used the account for less than a month. I'd like to request a pro-rated refund for the remaining 11 months.", fromName: "Viktor Sokolov", fromEmail: "v.sokolov@startup.ru", status: "open", category: "refund_request", daysAgo: 4 },

  // More general
  { subject: "How to integrate with Zapier?", body: "I'd like to connect your platform with Zapier to automate some workflows. Is there a Zapier integration available? If so, where can I find the setup documentation?", fromName: "Amy Chen", fromEmail: "amychen@workflow.co", status: "resolved", category: "general_question", daysAgo: 10 },
  { subject: "Is white-labelling available on any plan?", body: "We're building a product on top of your platform and need to remove your branding and use our own. Is white-labelling available? Which plan includes this feature?", fromName: "Marcus Johansson", fromEmail: "m.johansson@saas-builder.se", status: "open", category: "general_question", daysAgo: 0 },
  { subject: "Can I have multiple workspaces under one account?", body: "I manage clients separately and would like to keep their data isolated in separate workspaces. Can I create multiple workspaces under one billing account?", fromName: "Diane Moreau", fromEmail: "d.moreau@agency.fr", status: "resolved", category: "general_question", daysAgo: 14 },
  { subject: "What languages is the platform available in?", body: "We have a team across 5 countries. Is the platform available in French, German, Spanish, and Japanese in addition to English?", fromName: "Antonio García", fromEmail: "antonio.g@global-team.es", status: "open", category: "general_question", daysAgo: 2 },
  { subject: "How do I configure custom domains?", body: "I'd like to serve the platform from my own domain. Is custom domain configuration supported? I'm on the Business plan.", fromName: "Olga Petrova", fromEmail: "o.petrova@brand.ru", status: "resolved", category: "general_question", daysAgo: 8 },
  { subject: "Can we get an invoice with a different company name?", body: "The subscription is used by our subsidiary but the parent company needs to be on the invoice for accounting purposes. Can we customise the billing information?", fromName: "Tobias Werner", fromEmail: "t.werner@holding-group.de", status: "open", category: "general_question", daysAgo: 1 },
  { subject: "Do you have a status page?", body: "During the outage last week I had no way to know if the issue was on your end or mine. Do you have a public status page I can subscribe to for incident notifications?", fromName: "Keiko Watanabe", fromEmail: "k.watanabe@digital.jp", status: "resolved", category: "general_question", daysAgo: 11 },
  { subject: "Is it possible to schedule posts in advance?", body: "I want to prepare content for the whole month and schedule it to publish at specific times. Is scheduling functionality available in the current version?", fromName: "Lucas Martin", fromEmail: "lucas.martin@content.be", status: "open", category: "general_question", daysAgo: 3 },
  { subject: "How to revoke API keys?", body: "One of our developers left the company and we need to revoke their API key. I can't find a revoke or delete option in the API keys section of the dashboard.", fromName: "Hana Novak", fromEmail: "h.novak@security-ops.cz", status: "resolved", category: "general_question", daysAgo: 6 },
  { subject: "Do you offer phone support?", body: "We're dealing with a critical production issue that needs urgent resolution. Email support is too slow for our current situation. Do you offer phone or live chat support?", fromName: "Ryan Donnelly", fromEmail: "ryan.d@critical-ops.ie", status: "open", category: "general_question", daysAgo: 0 },

  // Mixed statuses
  { subject: "Account locked after multiple login attempts", body: "I forgot my password and attempted to reset it multiple times. Now my account is locked. The unlock email hasn't arrived even after 30 minutes.", fromName: "Florence Kone", fromEmail: "f.kone@dakar.sn", status: "open", category: "technical_question", daysAgo: 0 },
  { subject: "How do I enable two-factor authentication?", body: "I want to secure my account with 2FA. I've found the Security settings page but the toggle for two-factor authentication is greyed out. Why might this be?", fromName: "Sebastião Lima", fromEmail: "seb.lima@protect.br", status: "resolved", category: "general_question", daysAgo: 7 },
  { subject: "Invoice shows incorrect VAT amount", body: "My invoice for March shows 20% VAT but as a registered business in Germany we should be charged 0% under reverse charge rules. Could you re-issue the invoice with the correct VAT?", fromName: "Klaus Müller", fromEmail: "k.mueller@business-de.de", status: "open", category: "refund_request", daysAgo: 2 },
  { subject: "Data not loading after password change", body: "I changed my password yesterday. Now when I log in, the dashboard loads but no data is displayed – just empty tables and charts. Other users on our account see data normally.", fromName: "Miriam Oduya", fromEmail: "miriam.o@studio.ng", status: "resolved", category: "technical_question", daysAgo: 9 },
  { subject: "Can I import data from Notion?", body: "We currently use Notion for project management and want to migrate to your platform. Is there a direct Notion import or do I need to export to CSV first?", fromName: "Tom Eriksen", fromEmail: "t.eriksen@migrate.no", status: "open", category: "general_question", daysAgo: 1 },
  { subject: "Automated email contains broken image links", body: "The onboarding email sequence contains broken image links. The images were showing correctly last week. Users are reporting seeing red X placeholders instead of the images.", fromName: "Ana Rodrigues", fromEmail: "a.rodrigues@marketing.pt", status: "open", category: "technical_question", daysAgo: 2 },
  { subject: "Refund for pro plan – downgrading to free", body: "I've been on Pro for 6 months but I'm scaling back my business. I'd like to downgrade to the free plan and receive a partial refund for this month as I'm only 4 days in.", fromName: "Sam Okonjo", fromEmail: "sam.okonjo@freelancer.ng", status: "open", category: "refund_request", daysAgo: 0 },
  { subject: "Performance degraded since last week", body: "Page load times have increased significantly since around March 18th. Dashboard previously loaded in under 1 second, now taking 8–12 seconds. Our team of 50 is all experiencing this.", fromName: "Wei Zhang", fromEmail: "wei.zhang@techfirm.cn", status: "open", category: "technical_question", daysAgo: 4 },
  { subject: "What happens to my data if I downgrade?", body: "I'm considering downgrading from Business to Pro. Will I lose any data? Specifically I'm concerned about historical reports and audit logs that may be Business-only features.", fromName: "Laura Eriksson", fromEmail: "l.eriksson@careful.fi", status: "resolved", category: "general_question", daysAgo: 16 },
  { subject: "Login with Google not working", body: "I normally sign in with Google. Since yesterday clicking 'Continue with Google' opens the OAuth popup but after authorising it just closes with no login. Console shows a CORS error.", fromName: "Joel Mensah", fromEmail: "joel.mensah@accra.gh", status: "open", category: "technical_question", daysAgo: 1 },
  { subject: "Team member cannot access shared folders", body: "I've shared several folders with a team member but they can only see some of them. I've double-checked the permissions and they show as having access to all folders.", fromName: "Camille Leclerc", fromEmail: "c.leclerc@collab.fr", status: "open", category: "technical_question", daysAgo: 3 },
  { subject: "Is there a limit on the number of integrations?", body: "We're building a complex workflow with about 15 third-party integrations. Is there a limit on the number of active integrations per workspace on the Business plan?", fromName: "Takeshi Yamamoto", fromEmail: "t.yamamoto@workflow.jp", status: "resolved", category: "general_question", daysAgo: 12 },
  { subject: "Accidental account deletion – need data recovery", body: "A colleague accidentally deleted our workspace. Is there any way to recover the data? It was deleted about 2 hours ago. We have critical project data in there.", fromName: "Marie-Claire Fontaine", fromEmail: "mc.fontaine@urgent.fr", status: "open", category: "technical_question", daysAgo: 0 },
  { subject: "Charged for seats we don't use", body: "We reduced our team from 20 to 12 users last month but we're still being billed for 20 seats. I removed the users from the team settings but the invoice hasn't changed.", fromName: "Pieter van den Berg", fromEmail: "p.vdberg@company.nl", status: "open", category: "refund_request", daysAgo: 5 },
  { subject: "How to set up custom roles and permissions?", body: "We need granular access control – some users should be able to view but not edit, others can edit but not delete. Is a custom roles and permissions system available?", fromName: "Isabel Alves", fromEmail: "i.alves@permissions.br", status: "open", category: "general_question", daysAgo: 2 },
  { subject: "Duplicate entries appearing in database", body: "After a sync operation, we have approximately 3,000 duplicate entries in our database. The sync appears to have run twice. Can you check the sync logs on your end?", fromName: "Andrei Constantin", fromEmail: "a.constantin@datafix.ro", status: "open", category: "technical_question", daysAgo: 1 },
  { subject: "Notification preferences not saving", body: "I update my notification preferences and click save. The page confirms the changes were saved. But when I navigate away and return, the settings have reverted to the previous values.", fromName: "Sophia Andersson", fromEmail: "s.andersson@sweden.se", status: "resolved", category: "technical_question", daysAgo: 22 },
  { subject: "Can I embed the app in an iframe?", body: "We want to embed your app within our internal company portal using an iframe. Is this supported? Are there any X-Frame-Options or CSP restrictions that would prevent this?", fromName: "David Nakashima", fromEmail: "d.nakashima@intranet.jp", status: "open", category: "general_question", daysAgo: 2 },
  { subject: "Refund for add-on purchased by mistake", body: "I accidentally added the Analytics add-on when I was exploring the pricing page. I noticed immediately and want to remove it and get a refund. I haven't used it at all.", fromName: "Elena Vasquez", fromEmail: "e.vasquez@accidental.mx", status: "resolved", category: "refund_request", daysAgo: 3 },
  { subject: "How to generate an API token with limited scope?", body: "For security purposes, I want to generate an API token that only has read access to specific resources. Is scope-limited token generation supported?", fromName: "Nikolai Ivanov", fromEmail: "n.ivanov@security-first.ru", status: "open", category: "technical_question", daysAgo: 1 },
  { subject: "Discount not applied at renewal", body: "I was offered a 30% loyalty discount by your support team 3 months ago. It was applied to the first month but not to subsequent renewals. I have the email confirmation.", fromName: "Claudia Bianchi", fromEmail: "c.bianchi@loyal.it", status: "open", category: "refund_request", daysAgo: 2 },
  { subject: "How do I archive old projects?", body: "I have dozens of old completed projects cluttering my workspace. Is there an archive feature that would hide them from the main view without permanently deleting them?", fromName: "Finn Larsen", fromEmail: "finn.l@org.dk", status: "resolved", category: "general_question", daysAgo: 17 },
  { subject: "Content not appearing after publishing", body: "I published an article 2 hours ago but it's not visible to users who are not logged in. The status shows as 'Published'. Other articles published previously are visible.", fromName: "Abiodun Oyelaran", fromEmail: "a.oyelaran@publisher.ng", status: "open", category: "technical_question", daysAgo: 0 },
  { subject: "How long does a refund take to appear?", body: "My refund was approved 5 days ago (I received the confirmation email). It still hasn't appeared on my credit card statement. How long should I expect to wait?", fromName: "Catherine Blanc", fromEmail: "c.blanc@patient.fr", status: "resolved", category: "general_question", daysAgo: 5 },
  { subject: "Missing audit log entries", body: "Our compliance team has noticed that some user actions are not appearing in the audit log. Specifically, bulk delete operations performed via the API are not being logged.", fromName: "Haruto Kobayashi", fromEmail: "h.kobayashi@compliance.jp", status: "open", category: "technical_question", daysAgo: 3 },
];

async function main() {
  console.log(`Seeding ${tickets.length} tickets...`);

  for (const t of tickets) {
    const createdAt = new Date();
    createdAt.setDate(createdAt.getDate() - t.daysAgo);
    // Spread out tickets created on the same day by adding hours based on index
    createdAt.setHours(Math.floor(Math.random() * 23), Math.floor(Math.random() * 59));

    await prisma.ticket.create({
      data: {
        subject: t.subject,
        body: t.body,
        fromName: t.fromName,
        fromEmail: t.fromEmail,
        status: t.status as "open" | "resolved" | "closed",
        category: t.category as "general_question" | "technical_question" | "refund_request" | null,
        createdAt,
        updatedAt: createdAt,
      },
    });
  }

  console.log("Done.");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
